# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Game": "game.ipynb",
         "tmenv_root": "gbx.ipynb",
         "gbx_bytes_to_json": "gbx.ipynb",
         "gbx_data_from_url": "gbx.ipynb",
         "gbx_data_from_file": "gbx.ipynb",
         "gbx_time_to_ms": "gbx.ipynb",
         "parse_sample": "gbx.ipynb",
         "parse_ghost": "gbx.ipynb",
         "sanitize_map_name": "gbx.ipynb",
         "parse_map": "gbx.ipynb",
         "API_HEADERS": "gbx.ipynb",
         "map_url_from_uid": "gbx.ipynb",
         "map_from_url": "gbx.ipynb",
         "map_from_file": "gbx.ipynb",
         "ghost_wr_url_from_map_uid": "gbx.ipynb",
         "ghost_wr_from_map_uid": "gbx.ipynb",
         "ghost_from_url": "gbx.ipynb",
         "ghost_from_file": "gbx.ipynb",
         "map_from_uid": "gbx.ipynb",
         "Prefix": "prefix.ipynb",
         "SimpleValueParser": "socket.ipynb",
         "ListValueParser": "socket.ipynb",
         "build_parser": "socket.ipynb",
         "TelemetryParser": "socket.ipynb",
         "Socket": "socket.ipynb",
         "ActionHandler": "tmenv.ipynb",
         "DiscreteActionHandler": "tmenv.ipynb",
         "ContinuousActionHandler": "tmenv.ipynb",
         "MixedActionHandler": "tmenv.ipynb",
         "Tmenv": "tmenv.ipynb",
         "segment_dist": "trajectory.ipynb",
         "segment_dists": "trajectory.ipynb",
         "segment_project": "trajectory.ipynb",
         "Trajectory": "trajectory.ipynb",
         "MssCapture": "window.ipynb",
         "Window": "window.ipynb",
         "StateWrapper": "wrappers.ipynb",
         "VisualState": "wrappers.ipynb",
         "vec2np": "wrappers.ipynb",
         "vec2rotation": "wrappers.ipynb",
         "RotationEnvWrapper": "wrappers.ipynb",
         "XYZ": "wrappers.ipynb",
         "TrajectoryEnvWrapper": "wrappers.ipynb",
         "TelemetryState": "wrappers.ipynb",
         "WheelState": "wrappers.ipynb",
         "TrajectoryState": "wrappers.ipynb",
         "TrajectoryDoneWrapper": "wrappers.ipynb",
         "TrajectoryTravelRewardWrapper": "wrappers.ipynb"}

modules = ["game.py",
           "gbx.py",
           "prefix.py",
           "socket.py",
           "tmenv.py",
           "trajectory.py",
           "window.py",
           "wrappers.py"]

doc_url = "https://trackmania-ai.github.io/tmenv/"

git_url = "https://github.com/trackmania-ai/tmenv/tree/master/"

def custom_doc_links(name): return None
